# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none
pr:
 branches:
   include:
     - main

stages:

- stage: 'checker'
  condition: "and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))"
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  - job: 'checker_account'

    steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'
      enabled: false

    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
      displayName: 'Run a multi-line script'
- stage: 'Packaging'
  condition: "and(succeeded(), eq(variables['Build.Reason'], 'refs/tags/release.*'))"
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  - job: 'Packaging_account'

    steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'

    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
      displayName: 'Run a multi-line script'


